version: '3'
services:
  tiddlywiki:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./tiddlywiki:/var/lib/tiddlywiki
    restart: unless-stopped
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    environment:
      - PORT=${PORT:-8080}
      - DEBUG_LEVEL=${DEBUG_LEVEL:-none}
      #- PATH_PREFIX=${PATH_PREFIX:-/}
      #- NODE_MEM=128
      - USERNAME=${USERNAME:-user}
      - PASSWORD=${PASSWORD:-wiki}